language: scala
scala:
- 2.11.8
jdk:
- oraclejdk8
deploy:
  matrix:
  - provider: s3
    access_key_id: AKIAJ3OPJDYMRK75BICQ
    secret_access_key: &1
    secure: lF9rnHRmAf8ym9RsG8q7vCZcPEMgMyIykT/DIAUQe/9OrbQ5PEoMI2ZqYAuEj4fuN67vOR+cbN1a5Fn7UzU0jswJUP+d7gnfbRkQ0ExBcOtgVpWuPLeWSMccKhn67HDIJcd0mkaDYBqxuZC0h0Xr1+9/0PYGBlGzojEu3DSpTSZEEIV7GHAjqoEnZJ7jB0MXpXCfPauny3YVmU+rdC62900jJfF68FoslU7qtaTry2tp8E4ugJ0N9gr8RPGy2QM6wFa7jOHiK4o2WxDJGp5UT3VBo5P6EgmZDMFw25uwrCUfnNHHGqeVo0yVm1mOkFsi2HNu38xVIXx3LhQgVSnWTlFRxq9e1dM2L+nk+AgrWzd0oc4MhYz2sr8q9uviH5QfJKFXyyV8O6vCvrJaFQVfb0hIi3Y23qo8lneGFgfGO7+A4de2FPcxqYaNuY3nR6e371hXslC3Hch7Sr2QlepfC+9uXHdYQIgo2MTvG4TT6hjDVwmXdsOC2HKK3CAZpnTsmkHefBpQq697OZTVl5uDi6xOsQENIJIHGrqlBG22qVgx1YTXnKhlI9BfSotpU3Yr9YmvQNL3egZ/D28JisEEVMpiA4NPN1tTyo35CtUN9wRpE/j+6AvvKPra5VHQKj+9knjNpHkQKIIjcL00mDAaKQlaCJI/u26c7Yg+96AR6bc=
    local_dir: dpl_cd_upload
    skip_cleanup: true
    on: &2
      repo: schneist/CodeKommune
    bucket: codekommune
    region: eu-west-1
  - provider: codedeploy
    access_key_id: AKIAJ3OPJDYMRK75BICQ
    secret_access_key: *1
    bucket: codekommune
    key: codekommune_2.11-1.0-SNAPSHOT.jar
    bundle_type: jar
    application: CodeKommune
    deployment_group: CodeKommuneDG
    on: *2
  secret_access_key:
    secure: lF9rnHRmAf8ym9RsG8q7vCZcPEMgMyIykT/DIAUQe/9OrbQ5PEoMI2ZqYAuEj4fuN67vOR+cbN1a5Fn7UzU0jswJUP+d7gnfbRkQ0ExBcOtgVpWuPLeWSMccKhn67HDIJcd0mkaDYBqxuZC0h0Xr1+9/0PYGBlGzojEu3DSpTSZEEIV7GHAjqoEnZJ7jB0MXpXCfPauny3YVmU+rdC62900jJfF68FoslU7qtaTry2tp8E4ugJ0N9gr8RPGy2QM6wFa7jOHiK4o2WxDJGp5UT3VBo5P6EgmZDMFw25uwrCUfnNHHGqeVo0yVm1mOkFsi2HNu38xVIXx3LhQgVSnWTlFRxq9e1dM2L+nk+AgrWzd0oc4MhYz2sr8q9uviH5QfJKFXyyV8O6vCvrJaFQVfb0hIi3Y23qo8lneGFgfGO7+A4de2FPcxqYaNuY3nR6e371hXslC3Hch7Sr2QlepfC+9uXHdYQIgo2MTvG4TT6hjDVwmXdsOC2HKK3CAZpnTsmkHefBpQq697OZTVl5uDi6xOsQENIJIHGrqlBG22qVgx1YTXnKhlI9BfSotpU3Yr9YmvQNL3egZ/D28JisEEVMpiA4NPN1tTyo35CtUN9wRpE/j+6AvvKPra5VHQKj+9knjNpHkQKIIjcL00mDAaKQlaCJI/u26c7Yg+96AR6bc=
before_deploy:
- mkdir -p dpl_cd_upload

